# Generated by Django 5.2.16 on 2026-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='customlistitem',
            index=models.Index(fields=['custom_list', 'order'], name='lists_custo_custom__922a1e_idx'),
        ),
    ]
