# Generated by hand: backfill `order` from existing date_added ordering.

from django.db import migrations


def backfill_order(apps, schema_editor):
    """Give every existing list its current date_added order as a baseline."""
    CustomList = apps.get_model("lists", "CustomList")
    CustomListItem = apps.get_model("lists", "CustomListItem")

    for custom_list_id in CustomList.objects.values_list("id", flat=True):
        list_items = CustomListItem.objects.filter(
            custom_list_id=custom_list_id,
        ).order_by("date_added")
        for rank, list_item in enumerate(list_items):
            # Avoid a write for rows that already happen to match.
            if list_item.order != rank:
                CustomListItem.objects.filter(pk=list_item.pk).update(order=rank)


def noop_reverse(apps, schema_editor):
    """Nothing to undo; `order` reverts to its default with the field removal."""


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_customlistitem_order_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_order, noop_reverse),
    ]
