# Generated by Django 5.2.16 on 2026-09-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_backfill_customlistitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomListPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('custom_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='lists.customlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pinned_at'],
            },
        ),
        migrations.AddField(
            model_name='customlist',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_lists', through='lists.CustomListPin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customlistpin',
            index=models.Index(fields=['user', 'pinned_at'], name='lists_custo_user_id_006453_idx'),
        ),
        migrations.AddConstraint(
            model_name='customlistpin',
            constraint=models.UniqueConstraint(fields=('user', 'custom_list'), name='lists_customlistpin_unique_user_list'),
        ),
    ]
