# Generated by Django 5.2.16 on 2026-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0056_user_home_hide_unreleased'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='list_detail_sort_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='list_detail_sort',
            field=models.CharField(choices=[('date_added', 'Date Added'), ('title', 'Title'), ('media_type', 'Media Type'), ('custom', 'Custom Order')], default='date_added', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_sort__in', ['date_added', 'title', 'media_type', 'custom'])), name='list_detail_sort_valid'),
        ),
    ]
