# Generated by Django 5.2.16 on 2026-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0057_remove_user_list_detail_sort_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_detail_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('list_detail_layout__in', ['grid', 'table'])), name='list_detail_layout_valid'),
        ),
    ]
